# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1PGFCSI1UBB4vsAzK4YqV-AoSWy4XOZ
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = [x for x in numbers if x % 2 == 0]
print("Even Numbers:", even_numbers)

odd_numbers = [x for x in numbers if x % 2 != 0]
print("Odd Numbers:", odd_numbers)

squares = [x**2 for x in numbers]
print("Squares:", squares)

cubes = [x**3 for x in numbers]
print("Cubes:", cubes)

greater_than_5 = [x for x in numbers if x > 5]
print("Numbers greater than 5:", greater_than_5)

double_numbers = [x*2 for x in numbers]
print("Double Numbers:", double_numbers)